### ISSUE TITLE
Fetch specific commit from remote repo

### ISSUE THREAD

**Issue by RalfJung** [josh-project/josh#1034]
It would be nice to have a way to fetch a specific commit from the remote repo. Right now one can pull from a branch, but if one names a particular commit, then git will fetch *that commit*, not its josh-filtered version.

This would, for example, let us keep track of of what exactly the commit was that we pulled from last time.

**Comment by christian-schilling** [comment]
Check out `tests/proxy/clone_sha.t`
I think that's the feature you are looking for.

**Comment by christian-schilling** [comment]
Like @LMG said, this syntax will result a repo that has no branches except one fake one pointing to the filtered commit given by the sha with `HEAD` pointing to it. This is mostly intended to be used for CI to get "sandboxed" trees of specific commits.

Is that what you need @RalfJung or did I misunderstand?

Also if you are just interested in the sha and don't need the actual repo you might want to look into the GraphQL API. It enables querying all sorts of things about (filtered) repos.
There is not much docs on that, but the graphiql interface shows auto generated Schema documentation.

**Comment by RalfJung** [comment]
You can [see here](https://github.com/rust-lang/miri/blob/ee0e990ed3c1b00be45e3dca979824ee0bbcc551/miri#L114L124) how we are using this.  Basically we want to be sure we know the commit it fetched from, and it's also nice to let the user control that commit rather than hard-coding latest master.

I thought the GraphQL API was a github thing, I didn't know josh also has some support for that. But it seems overkill for thise usecase.

**Comment by christian-schilling** [comment]
Ah, interesting. You are certainly not the first wanting to do something like this (noting down original sha on sync @LMG).
When doing this you might want to add `:exclude[::rust-version]` to your `JOSH_FILTER` to avoid conflicts in that file.

**Comment by RalfJung** [comment]
The file will never change in the monorepo, only in the miri subrepo, so this should be fine. (Also we want the file in the subrepo so excluding it sounds wrong?)

**Comment by christian-schilling** [comment]
I think the question has been answered.
