### ISSUE TITLE
Tests are failing when using `tree >= 2.1.0 `

### ISSUE THREAD

**Issue by sinavir** [josh-project/josh#1263]
tree program changelog for version 2.1.0 state:
> Updated the totals reporting code to also include in the total the file or directory that is being listed. This should make a correct report when doing something like 'tree *'.

Source : https://mama.indstate.edu/users/ice/tree/changes.html

It makes tests fail on my computer with this kind of errors:
```
--- tests/filter/ambigous_merge.t
+++ tests/filter/ambigous_merge.t.err
@@ -105,7 +105,7 @@
       |-- file2
       `-- fileX

-  2 directories, 7 files
+  3 directories, 7 files

```

**Comment by sinavir** [comment]
I believe I am not using the provided shell.nix (thus the wrong tree version), but I am trying to put the tests in the nix package for josh as well as updating it and writing a module so I have to use the current version of tree in nixos-unstable.

**Comment by LMG** [comment]
I don't think the nix file is maintained. Could you try using ./tester.sh ?

**Comment by sinavir** [comment]
Indeed It works inside the docker. I will try to fix `shell.nix` and submit a PR if I have time

**Comment by LMG** [comment]
Thank you :)
