### ISSUE TITLE
Rust 1.80 support

### ISSUE THREAD

**Issue by flokli** [josh-project/josh#1353]
Nixpkgs is [updating to Rust 1.80](https://github.com/NixOS/nixpkgs/issues/332957), and we noticed josh stops building with Rust 1.80.

As described in the issue, there's an unfixable build regression in rustc https://github.com/rust-lang/rust/issues/127343, usually requiring bumping a bump of the `time` crate:

```
error[E0282]: type annotations needed for `Box<_>`
  --> /build/josh-23.12.04-vendor.tar.gz/time/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

```

**Comment by flokli** [comment]
I sent a PR at https://github.com/josh-project/josh/pull/1354.

Would be great if you can tag a release containing this fix once it landed.

**Comment by flokli** [comment]
Thanks! Can you create a tag containing this?

**Comment by christian-schilling** [comment]
> Thanks! Can you create a tag containing this?

done

**Comment by flokli** [comment]
Thanks!
