### ISSUE TITLE
Changing a mapping path adds the old files/folders

### ISSUE THREAD

**Issue by LMG** [josh-project/josh#251]
Starting from a workspace.josh looking like 

`a = :/a`

and editing in one commit to 

`b = :/a` 

will duplicate the files from a in the workspace directory instead of just updating the mapping.
#250 demonstrates this behaviour in a test. Note the duplicated file2.

**Comment by christian-schilling** [comment]
I think we agreed that this is intended or at least accepted behavior. Users are expected to move the files in the workspace tree themselves.
