### ISSUE TITLE
Inconsistency and lost changes on push with certain filters

### ISSUE THREAD

**Issue by LMG** [josh-project/josh#645]
`::a/:exclude[::a/b]`  should be equivalent to `a = :/a:exclude[::b]`.

With the first one, a modification to a file `a/c` will be lost on push. 

With the second one, it works.

**Comment by christian-schilling** [comment]
I tried to reproduce this with a test case but it seems the behavior is correct.
[reverse_hide_edit2.t](https://github.com/josh-project/josh/files/8225960/reverse_hide_edit2.t.txt)

**Comment by christian-schilling** [comment]
fixed in #682
