### ISSUE TITLE
hyper-cgi-test-server: command not found

### ISSUE THREAD

**Issue by benblo** [josh-project/josh#982]
I'm following the [workspace tutorial](https://josh-project.github.io/josh/guide/workspaces.html), and getting stuck at the "Serving the git repo" step:
> hyper-cgi-test-server: command not found

I've installed josh through Docker as instructed; should the server be part of the container?

Edit: found this [elsewhere in the docs](https://josh-project.github.io/josh/contributing/testing.html#1-setup-the-test-environment):
> cargo install hyper_cgi --features=test-server

... but I get a compile error:
```
   Compiling hyper_cgi v22.4.15
error[E0107]: this struct takes 0 lifetime arguments but 1 lifetime argument was supplied
  --> C:\Users\Ben\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper_cgi-22.4.15\src\bin\hyper-cgi-test-server.rs:34:28
   |
34 |     static ref ARGS: clap::ArgMatches<'static> = parse_args();
   |                            ^^^^^^^^^^--------- help: remove these generics
   |                            |
   |                            expected 0 lifetime arguments
   |
note: struct defined here, with 0 lifetime parameters
```

**Comment by benblo** [comment]
I also tried using a [gitea](https://gitea.io/) server instead... no luck. Cloning from the josh-proxy hangs forever.
Here's the command I used (3000 is gitea's default port):
> docker run -d --network="host" -e JOSH_REMOTE=http://localhost:3000 -v josh-vol:$(pwd)/git_data joshproject/josh-proxy:latest

I don't understand what `--network="host"` is supposed to do, how do we know what port the proxy is supposed to listen on, how do we translate from 3000 to 8000?

I'm not sure I understand what `hyper-cgi-test-server` is supposed to do, am I wrong to assume that any other http-friendly git server would work the same for the rest of the tutorial?

**Comment by LMG** [comment]
Right, @christian-schilling noticed the test server was borked last week or so. I need to fix it (and our CI, this shouldn't have happened). You're right though, you can use any http-compatible git server for this.

The reason I used this one is because it's what we use in our tests, and the tutorial code is run like one of our integration tests.

**Comment by christian-schilling** [comment]
The reason your attempt with gitlab does not work is docker networking. You have to use `host.docker.internal` instead of `localhost`. Hope that helps.

**Comment by benblo** [comment]
> Right, @christian-schilling noticed the test server was borked last week or so. I need to fix it

Ah, glad to hear I'm not crazy :) !


> The reason your attempt with gitea does not work is docker networking. You have to use `host.docker.internal` instead of `localhost`. Hope that helps.

Thanks, that does help, I never would have guessed that! Here's what worked (I also had to remove the `--network="host"` arg):

    docker run -d -p 8000:8000 -e JOSH_REMOTE=http://host.docker.internal:3000 -v josh-vol:$(pwd)/git_data joshproject/josh-proxy:latest

Next step: credentials! How do I actually push something, through the proxy, against a server that requires authentication? The [github example](https://josh-project.github.io/josh/guide/gettingstarted.html) actually doesn't cover that, and my gitea server (unlike hyper-cgi-test-server I imagine) requires authentication.

I apologize if this is actually unrelated to josh, and more of another docker networking noob question. Who should actually hold the credentials: my local config? the josh-proxy container? 🙄

**Comment by LMG** [comment]
When the josh proxy points to your server that requires credentials, the proxy will prompt you for credentials. It will then forward them to the server. This should thus be transparent.

**Comment by benblo** [comment]
Doesn't work for me, not transparently at least because I can't figure it out 😄, sorry!

I setup a github proxy as in the tutorial, and clone one of my own private repos (without any fancy filtering, just straight clone through the proxy):
```
docker run -d -p 8000:8000 -e JOSH_REMOTE=https://github.com -v josh-vol:$(pwd)/git_data joshproject/josh-proxy:latest
git clone http://localhost:8000/benblo/josh-test-monorepo.git
```

Then when I add a commit and push against the josh proxy, I don't get a prompt for credentials, but a `No anonymous write access` error.
```
remote: josh-proxy
remote: response from upstream:
remote: remote: No anonymous write access.
remote: fatal: Authentication failed for 'https://github.com/benblo/josh-test-monorepo.git/'
remote:
remote:
remote: error: hook declined to update refs/heads/main
To http://localhost:8000/benblo/josh-test-monorepo.git
 ! [remote rejected] main -> main (hook declined)
error: failed to push some refs to 'http://localhost:8000/benblo/josh-test-monorepo.git'
```

I tried adding by username to the url:
```
docker run -d -p 8000:8000 -e JOSH_REMOTE=https://benblo@github.com -v josh-vol:$(pwd)/git_data joshproject/josh-proxy:latest
```
and now I get `Invalid username or password`:
```
remote: josh-proxy
remote: response from upstream:
remote: remote: Invalid username or password.
remote: fatal: Authentication failed for 'https://github.com/benblo/josh-test-monorepo.git/'
```

If I do any of this without the proxy (straight clone from/push to github.com), everything works fine so my credentials are there.
I would be happy to manually insert new credentials using `git credential-manager-core store`, but I'm confused as to where to do that, what URL to use (localhost:8000?), etc.
Or maybe I need to wipe my credentials and start over? which I also don't really know how to do... where are the josh-proxy credentials stored?

**Comment by LMG** [comment]
For github (or any server that allows you to fetch without credentials I guess) you  have to add the option `--require-auth` to the proxy if you want to be able to push. I see it is missing from the documentation, my bad.

The credentials will be temporarily held by the proxy once it prompts you for them. I mean, from your point of view, it should be like managing credentials for any other git server I suppose, you have them locally and the server prompts you for them. 

If you you use the cache option (-c 60 for example) josh will hold your https credentials to validate them without having to fetch from the server for the duration that you give (here 60 seconds). 

If your crendentials become invalid you might have to flush the credential cache by accessing `https://your-josh-server/flush`, though I think after the caching interval that should be unnecessary.

**Comment by benblo** [comment]
> you have to add the option `--require-auth` to the proxy

... where?

**Comment by LMG** [comment]
```docker run -d -p 8000:8000 -e JOSH_EXTRA_OPTS="--require-auth"  -e JOSH_REMOTE=https://github.com -v josh-vol:$(pwd)/git_data joshproject/josh-proxy:latest
```

**Comment by LMG** [comment]
I just tested this locally pointing to github and it works. You of course have to setup an access token in github like you normally would. (https://github.com/settings/tokens)

**Comment by benblo** [comment]
YES! Thank you, it finally works 🙇 ! The `JOSH_EXTRA_OPTS` bit was what I was looking for.

**Comment by LMG** [comment]
Might need to update the documentation. Sorry about this.

**Comment by LMG** [comment]
The CGI test server thing will be solved by https://github.com/josh-project/josh/pull/995 and the documentation updated in https://github.com/josh-project/josh/pull/999
